language: java

sudo: required

##Start xvfb to allow visibility of the application to integration tests
before_script:
  # Fix a problem with apt-get failing later, see http://docs.travis-ci.com/user/installing-dependencies/#Installing-Ubuntu-packages
  - sudo apt-get update -qq
  - sudo add-apt-repository -y ppa:thedsweb/yawls-opencv
  - sudo apt-get update
  - sudo apt-get install --force-yes --yes libcv-dev
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

##skip installation step
install: true

## Run Integration tests
script: "mvn verify"